export const MOCK_USER = {
  id: 1,
  firstName: "John",
  lastName: "Maxwell",
  email: "glenn@example.com",
  phoneNumber: "0244123456",
  role: "PASSENGER",
};

export const MOCK_DRIVER = {
  id: 2,
  firstName: "Kofi",
  lastName: "Annan",
  email: "driver@example.com",
  phoneNumber: "0244987654",
  role: "DRIVER",
  busId: 101, // Driver needs a bus assigned
};

export const MOCK_ROUTES = [
  {
    id: 1,
    routeId: 1,
    name: "Lapaz - Circle",
    origin: "Lapaz",
    destination: "Circle",
    startStopName: "Lapaz Station",
    endStopName: "Circle Station",
    stopCount: 5,
    distanceKm: 250,
    estimatedDurationMinutes: 270,
    description: "Direct express service between Accra and Kumasi.",
    fare: 150.0,
    duration: "4h 30m",
    distance: "250km",
    stops: [
      { id: 1, name: "Accra Central", latitude: 5.5486, longitude: -0.2012 },
      { id: 2, name: "Achimota", latitude: 5.6219, longitude: -0.2322 },
      { id: 3, name: "Nsawam", latitude: 5.8089, longitude: -0.3503 },
      { id: 4, name: "Nkawkaw", latitude: 6.5511, longitude: -0.7634 },
      { id: 5, name: "Kumasi Kejetia", latitude: 6.6953, longitude: -1.6241 },
    ],
  },
  {
    id: 2,
    routeId: 2,
    name: "Circle - Madina",
    origin: "Kwame Nkrumah Circle",
    destination: "Madina Terminal",
    startStopName: "Kwame Nkrumah Circle",
    endStopName: "Madina Terminal",
    stopCount: 5,
    distanceKm: 12,
    estimatedDurationMinutes: 45,
    description: "Frequent urban service through Ridge and Legon.",
    fare: 15.0,
    duration: "45m",
    distance: "12km",
    stops: [
      { id: 6, name: "Circle", latitude: 5.5598, longitude: -0.2097 },
      { id: 7, name: "Ridge", latitude: 5.5671, longitude: -0.1944 },
      {
        id: 8,
        name: "37 Military Hospital",
        latitude: 5.5898,
        longitude: -0.1873,
      },
      { id: 9, name: "Legon", latitude: 5.6508, longitude: -0.1869 },
      { id: 10, name: "Madina", latitude: 5.6681, longitude: -0.1641 },
    ],
  },
  {
    id: 3,
    routeId: 3,
    name: "Tema - Accra",
    origin: "Tema Station",
    destination: "Accra Central",
    startStopName: "Tema Station",
    endStopName: "Accra Central",
    stopCount: 5,
    distanceKm: 25,
    estimatedDurationMinutes: 60,
    description: "Coastal route connecting the port city to the capital.",
    fare: 18.0,
    duration: "1h",
    distance: "25km",
    stops: [
      { id: 11, name: "Tema Community 1", latitude: 5.6384, longitude: 0.0039 },
      { id: 12, name: "Nungua", latitude: 5.6033, longitude: -0.0769 },
      { id: 13, name: "Teshie", latitude: 5.5833, longitude: -0.1001 },
      { id: 14, name: "La", latitude: 5.5619, longitude: -0.1542 },
      { id: 15, name: "Accra Central", latitude: 5.5486, longitude: -0.2012 },
    ],
  },
];

export const MOCK_SCHEDULES = [
  {
    id: 1,
    scheduleId: 1,
    routeId: 1,
    routeName: "Accra - Kumasi Express",
    departureTime: "08:00 AM",
    startTime: "08:00 AM",
    arrivalTime: "12:30 PM",
    dayOfWeek: "Daily",
    days: "Daily",
    busNumber: "GR-1234-22",
    availableSeats: 45,
    status: "ON_TIME",
  },
  {
    id: 2,
    scheduleId: 2,
    routeId: 1,
    routeName: "Accra - Kumasi Express",
    departureTime: "10:30 AM",
    startTime: "10:30 AM",
    arrivalTime: "03:00 PM",
    dayOfWeek: "Mon, Wed, Fri",
    days: "Mon, Wed, Fri",
    busNumber: "GR-5678-22",
    availableSeats: 12,
    status: "DELAYED",
  },
  {
    id: 3,
    scheduleId: 3,
    routeId: 2,
    routeName: "Circle - Madina",
    departureTime: "07:00 AM",
    startTime: "07:00 AM",
    arrivalTime: "07:45 AM",
    dayOfWeek: "Daily",
    days: "Daily",
    busNumber: "GW-9988-23",
    availableSeats: 5,
    status: "ON_TIME",
  },
];

export const MOCK_TICKETS = [
  {
    id: 1,
    ticketId: 1,
    ticketCode: "TKT-7890-ABC",
    routeId: 1,
    routeName: "Tesano - Circle",
    departureTime: "08:00 AM",
    travelDate: "2026-04-15",
    date: "2026-04-15",
    origin: "Tesano",
    destination: "Circle",
    seatNumber: "A12",
    passengers: 1,
    fare: 150.0,
    amount: 150.0,
    status: "PAID",
    purchaseDate: "2026-04-10T14:30:00",
  },
  {
    id: 2,
    ticketId: 2,
    ticketCode: "TKT-4567-XYZ",
    routeId: 2,
    routeName: "Circle - Madina",
    departureTime: "07:00 AM",
    travelDate: "2026-04-14",
    date: "2026-04-14",
    origin: "Circle",
    destination: "Madina Terminal",
    seatNumber: "B05",
    passengers: 1,
    fare: 15.0,
    amount: 15.0,
    status: "USED",
    purchaseDate: "2026-04-14T06:45:00",
  },
  {
    id: 3,
    ticketId: 3,
    ticketCode: "TKT-1234-EFG",
    routeId: 3,
    routeName: "Tema - Accra",
    departureTime: "10:00 AM",
    travelDate: "2026-04-16",
    date: "2026-04-16",
    origin: "Tema Station",
    destination: "Accra Central",
    seatNumber: "C03",
    passengers: 1,
    fare: 18.0,
    amount: 18.0,
    status: "BOOKED",
    purchaseDate: "2026-04-13T09:15:00",
  },
];

export const MOCK_BUS_LOCATIONS = [
  {
    busId: 101,
    routeId: 1,
    latitude: 5.6037,
    longitude: -0.187,
    timestamp: new Date().toISOString(),
    busNumber: "GR-1234-22",
  },
  {
    busId: 102,
    routeId: 2,
    latitude: 5.5598,
    longitude: -0.2097,
    timestamp: new Date().toISOString(),
    busNumber: "GW-9988-23",
  },
  {
    busId: 103,
    routeId: 3,
    latitude: 5.6384,
    longitude: 0.0039,
    timestamp: new Date().toISOString(),
    busNumber: "GT-4455-21",
  },
];

export const MOCK_TRIPS = [
  {
    id: 1,
    tripId: 1,
    busId: 101,
    routeId: 1,
    routeName: "Tesano - Circle",
    status: "IN_PROGRESS",
    startTime: "2026-04-14T08:00:00",
    scheduledDeparture: "08:00 AM",
    scheduledArrival: "12:30 PM",
    origin: "Tesano",
    destination: "Circle",
    passengerCount: 32,
    scheduleId: 1,
  },
  {
    id: 2,
    tripId: 2,
    busId: 101,
    routeId: 2,
    routeName: "Circle - Madina",
    status: "SCHEDULED",
    startTime: "2026-04-14T10:00:00",
    scheduledDeparture: "10:00 AM",
    scheduledArrival: "11:00 AM",
    origin: "Kwame Nkrumah Circle",
    destination: "Madina Terminal",
    passengerCount: 0,
    scheduleId: 3,
  },
];
