spring.application.name=BusTracking

spring.profiles.active=qa

server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false

jwt.secret=9jxaxR3nqUiU8BmCNKEQ5cK23kAh4aM7vPpSzjWtBZQ=
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=604800000
